version: 2

models:
  - name: clean_sales   
    description: "Cleaned sales data from fact_retail_sales"
    columns:
      - name: sale_id
        description: "Unique sale identifier"
        tests:
          - not_null
          - unique
      - name: total_amount
        description: "Total sale amount"
        tests:
          - not_null
      - name: date
        description: "Sale date"
        tests:
          - not_null
      - name: store_id
        description: "Store ID"
        tests:
          - not_null
      - name: product_id
        description: "Product ID"
        tests:
          - not_null
